trigger:
  branches:
    include:
      - refs/heads/master
      - refs/tags/*

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

# Test the app
- template: ci/azure-test-stable.yml
  parameters:
    name: test_qrgen
    displayName: Test qrgen

# Release Windows
- template: ci/azure-release.yml
  parameters:
    name: dist_windows
    displayName: "Distribute Windows Binary"
    vmImage: vs2017-win2016

# Release Mac
- template: ci/azure-release.yml
  parameters:
    name: dist_darwin
    displayName: "Distribute Darwin Binary"
    vmImage: macOS-10.13
