trigger:
  branches:
    include:
    - refs/heads/master
    - refs/tags/*

jobs:
  - job: run_rustfmt
    displayName: "Run rust fmt"
    pool:
        vmImage: ubuntu-16.04
    steps:
    - template: ci/azure-install-rust.yml
      parameters:
        rust_version: stable
    - script: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting
  
  - job: run_cargo_test
    displayName: "cargo test"
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)
    steps:
    - template: ci/azure-install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo test
      displayName: Cargo test
  
  - job: create_binaries
    displayName: "Create release binaries"
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
          releaseName: "release_ubuntu"
        MacOS:
          vmImage: macOS-10.13
          releaseName: "release_darwin"
        Windows:
          vmImage: vs2017-win2016
          releaseName: "release_windows"
    pool:
      vmImage: $(vmImage)
    steps:
    - template: ci/azure-install-rust.yml
      parameters:
        rust_version: stable
    - script: cargo build --release
      displayName: cargo build release
    - template: ci/azure-publish-artifact.yml
      parameters:
        name: $(releaseName)

  - job: deploy_release
    displayName: "Deploy release"
    dependsOn:
      - create_binaries
      - run_rustfmt
      - run_cargo_test
    steps:
      - task: DownloadPipelineArtifact@0
        displayName: "Download release - ubuntu"
        inputs:
          artifactName: release_ubuntu
          targetPath: $(System.DefaultWorkingDirectory)/ubuntu
      - task: ArchiveFiles@2
        displayName: Gather assets release_ubuntu
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/ubuntu
          archiveType: 'zip'
          archiveFile: $(System.DefaultWorkingDirectory)/deploy/release_ubuntu.zip'
      - task: DownloadPipelineArtifact@0
        displayName: "Download release - darwin"
        inputs:
          artifactName: release_darwin
          targetPath: $(System.DefaultWorkingDirectory)/darwin
      - task: ArchiveFiles@2
        displayName: Gather assets release_darwin
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/darwin
          archiveType: 'zip'
          archiveFile: $(System.DefaultWorkingDirectory)/deploy/release_darwin.zip'
      - task: DownloadPipelineArtifact@0
        displayName: "Download release - windows"
        inputs:
          artifactName: release_windows
          targetPath: $(System.DefaultWorkingDirectory)/windows
      - task: ArchiveFiles@2
        displayName: Gather assets release_windows
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/windows
          archiveType: 'zip'
          archiveFile: $(System.DefaultWorkingDirectory)/deploy/release_windows.zip'