trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

# Test the app
- template: ci/azure-test-stable.yml
  parameters:
    name: test_qrgen
    displayName: Test qrgen
