[package]
name = "qrgen"
version = "0.5.0"
authors = ["ian-hamlin <ian@ihamlin.co.uk>"]
edition = "2018"

[dependencies]
structopt = "0.3"
qrcodegen = "1.6.0"
log = "0.4.11"
env_logger = "0.8.2"
csv = "1.1.5"
rayon = "1.5.0"
png = "0.16.8"
itertools = "0.10.0"