[package]
name = "qrgen"
version = "0.5.0"
authors = ["ian-hamlin <ian@ihamlin.co.uk>"]
edition = "2018"

[dependencies]
structopt = "0.3.26"
qrcodegen = "1.8.0"
log = "0.4.17"
env_logger = "0.9"
csv = "1.1.6"
rayon = "1.5.3"
png = "0.17.5"
itertools = "0.10.3"