jobs:
- job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo build --release
      - template: ci/azure-create-tarball.yml
        parameters:
          name: ${{ parameters.name }}