jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
    - template: azure-install-rust.yml
    - script: cargo build --release
    - template: azure-create-tarball.yml
      parameters:
        name: ${{ parameters.name }}